version: "2"
services:
  app_nama:
    build: .
    links:
      - db_nama
    ports:
      - "5000:5000"
  db_nama:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: yubelajar
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro